# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
commands:
  print_pipeline_id:
    description: "A very simple command to print pipeline Id."
    parameters:
      my_param:
        type: string
        default: "xiaosha test param!!"
    steps:
      - run: echo << parameters.my_param >>
      - run: echo $CIRCLE_WORKFLOW_ID
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
            - /lib
      - run: npm run build
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache: # will download it from the internet, which was store by save_cache
          keys:
            - "npm-packages" # I cannot find it : (
      # - run: ls src
      - run: npm i
      - run: npm run build
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit
  fail_on_purpose_and_catch:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: return 1 # make it fail
      - run:
          name: Print some error logs.
          command: echo "OH NO! ERRORS!"
          when: on_fail
  test_command:
    docker:
      - image: cimg/base:2020.01
    steps:
      - print_pipeline_id:
          my_param: "xing test param!!"
  save_file_to_workspace:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Hello world! Hello Xiaosha!" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  read_file_from_workspace:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
      - run: ls /
  test_env_var:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: "echo an env var that is part of my project"
          command: |
            echo $MY_ENV_VAR

# Orchestrate or schedule a set of jobs
workflows:
  my_ci_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - build
            - test
  test_playground:
    jobs:
      - test_env_var
      - test_command
      # - fail_on_purpose_and_catch
      - save_file_to_workspace
      - read_file_from_workspace:
          requires:
            - save_file_to_workspace